name: Deploy to Remote

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          cache: 'gradle'
          distribution: 'adopt'
      - name: Build & copy jar
        run: ./gradlew -PskipBuild=dev-launcher,snbt-builder,velocity :phantazm-server:copyJar
      - name: Zip server files
        run: |
          cd ./run/server-1
          tar -czf /tmp/server.tar.gz server.jar libs
